---
name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest
    name: Check Style
    env:
      MIX_ENV: test
      CI: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.3'
      - run: mix deps.get --only dev
      - run: mix format --check-formatted
      - run: mix credo --strict

  test-oldest:
    runs-on: ubuntu-20.04
    name: Tests on oldest version
    env:
      MIX_ENV: test
      CI: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '21'
          elixir-version: '1.11.4'
      - run: rm mix.lock
      - run: mix deps.get
      - run: mix compile --force --warnings-as-errors
      - run: mix test

  test:
    runs-on: ubuntu-latest
    name: Tests on latest version
    env:
      MIX_ENV: test
      CI: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.3'
      - run: rm mix.lock
      - run: mix deps.get
      - run: mix compile --force --warnings-as-errors
      - run: mix test
